### ISSUE TITLE
Module not showing in Blesta

### ISSUE THREAD

**Issue by omgitslurch** [gogetssl/blesta-module#2]
I've followed the instructions to install the Plugin so that it shows and works in Blesta. However, when I go to the Modules section in Blesta it is not listed at all in the modules to install section.

Have checked the and it is in the correct path as all the modules that come with Blesta which it recognises. Not seeing any errors or failures in any logs.

The server is running the following.
CloudLinux 8.3
OpenLiteSpeed 1.7.9
PHP 7.4.16
MariaDB 10.4.17

**Comment by kdg1992** [comment]
For me the same.
Im using Blesta 5.0.4

**Comment by kanenses** [comment]
+1

**Comment by vlad-evg** [comment]
Please provide FTP access via the ticket and developers would check. We double checked on our side and it is working.

**Comment by vlad-evg** [comment]
https://github.com/gogetssl/blesta-module/releases/tag/v2.1.1

That release should fix the issues, let us know if more issues
